USE DATABASE IPL_ANALYTICS;
USE SCHEMA RAW;
USE WAREHOUSE DEV_WH;

-- Table 1: Deliveries (Ball-by-ball data)
CREATE OR REPLACE TABLE DELIVERIES (
    MATCH_ID INTEGER,
    INNING INTEGER,
    BATTING_TEAM VARCHAR(100),
    BOWLING_TEAM VARCHAR(100),
    OVER INTEGER,
    BALL INTEGER,
    BATSMAN VARCHAR(100),
    NON_STRIKER VARCHAR(100),
    BOWLER VARCHAR(100),
    IS_SUPER_OVER INTEGER,
    WIDE_RUNS INTEGER,
    BYE_RUNS INTEGER,
    LEGBYE_RUNS INTEGER,
    NOBALL_RUNS INTEGER,
    PENALTY_RUNS INTEGER,
    BATSMAN_RUNS INTEGER,
    EXTRA_RUNS INTEGER,
    TOTAL_RUNS INTEGER,
    PLAYER_DISMISSED VARCHAR(100),
    DISMISSAL_KIND VARCHAR(50),
    FIELDER VARCHAR(100)
);

-- Table 2: Matches (Match-level data)
CREATE OR REPLACE TABLE MATCHES (
    ID INTEGER,
    SEASON VARCHAR(10),
    CITY VARCHAR(100),
    DATE VARCHAR(20),
    TEAM1 VARCHAR(100),
    TEAM2 VARCHAR(100),
    TOSS_WINNER VARCHAR(100),
    TOSS_DECISION VARCHAR(20),
    RESULT VARCHAR(50),
    DL_APPLIED INTEGER,
    WINNER VARCHAR(100),
    WIN_BY_RUNS INTEGER,
    WIN_BY_WICKETS INTEGER,
    PLAYER_OF_MATCH VARCHAR(100),
    VENUE VARCHAR(200),
    UMPIRE1 VARCHAR(100),
    UMPIRE2 VARCHAR(100),
    UMPIRE3 VARCHAR(100)
);

-- Table 3: Teams
CREATE OR REPLACE TABLE TEAMS (
    TEAM_NAME VARCHAR(100)
);

-- Table 4: Team Home/Away Stats
CREATE OR REPLACE TABLE TEAMWISE_HOME_AWAY (
    TEAM VARCHAR(100),
    HOME_WINS INTEGER,
    AWAY_WINS INTEGER,
    HOME_MATCHES INTEGER,
    AWAY_MATCHES INTEGER,
    HOME_WIN_PERCENTAGE FLOAT,
    AWAY_WIN_PERCENTAGE FLOAT
);

-- Table 5: Batting Statistics (Pre-aggregated)
CREATE OR REPLACE TABLE BATTING_STATS (
    BATSMAN VARCHAR(100),
    TOTAL_RUNS INTEGER,
    OUT INTEGER,
    NUMBER_OF_BALLS INTEGER,
    AVERAGE FLOAT,
    STRIKE_RATE FLOAT
);

-- Verify tables created
SHOW TABLES IN SCHEMA IPL_ANALYTICS.RAW;