USE DATABASE IPL_ANALYTICS;
USE SCHEMA RAW;
USE WAREHOUSE DEV_WH;

-- Check row counts after loading
SELECT 'DELIVERIES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DELIVERIES
UNION ALL
SELECT 'MATCHES', COUNT(*) FROM MATCHES
UNION ALL
SELECT 'TEAMS', COUNT(*) FROM TEAMS
UNION ALL
SELECT 'TEAMWISE_HOME_AWAY', COUNT(*) FROM TEAMWISE_HOME_AWAY
UNION ALL
SELECT 'BATTING_STATS', COUNT(*) FROM BATTING_STATS;

-- Preview data
SELECT * FROM DELIVERIES LIMIT 5;
SELECT * FROM MATCHES LIMIT 5;